server:
  app_name: "Authorization service"
  port: ":8080"
  debug: true
  secret_path: "secrets/secret.txt"
database:
  user: "Cracher"
  password: "12345"
  host: "db"
  port: "5432"
  name: "auth"
  ssl_mode: "disable"
